(function(g){var window=this;var Vpa=function(a,b){return g.Ub(a,b)},F5=function(){},Wpa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},Xpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Hd&&"function"==typeof a.Hd)var c=a.Hd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Ma(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=Wpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},G5=function(a){g.mn(a,"zx",g.bd());
return a},H5=function(a,b,c){g.La(c)||(c=[String(c)]);
g.rn(a.l,b,c)},I5=function(a){return(a=g.Lo(a))?new ActiveXObject(a):new XMLHttpRequest},J5=function(a,b){return b+" ["+a.ba+" "+a.F+" "+a.getStatus()+"]"},Ypa=function(a){return"content-type"==a.toLowerCase()},K5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.C&&(g.w.clearTimeout(a.C),a.C=null)},Zpa=function(a){return g.Md&&g.nd(9)&&g.Fa(a.timeout)&&g.Da(a.ontimeout)},L5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},M5=function(a,b){if(a.g){K5(a);
var c=a.g,d=a.P[0]?g.Ha:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},N5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;L5(a);M5(a)},O5=function(a){return a.g?a.g.readyState:0},P5=function(a){if(a.i&&"undefined"!=typeof g.GY)if(a.P[1]&&4==O5(a)&&2==a.getStatus())J5(a,"Local request error detected and ignored");
else if(a.D&&4==O5(a))g.Ig(a.iw,0,a);else if(a.dispatchEvent("readystatechange"),4==O5(a)){J5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!$pa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<O5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";L5(a)}}finally{M5(a)}}},Q5=function(a){g.Sf.call(this);
this.headers=new g.an;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.C=null;this.Z="";this.I=this.R=!1},R5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},aqa=function(a,b){var c=[];
g.Wk(b,function(d){try{var e=g.$o.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.Zo(e)&&c.push(d):c.push(d)},a);
return c},bqa=function(a,b){var c=aqa(a,b);
(0,g.B)(c,function(d){g.$o.prototype.remove.call(this,d)},a)},S5=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},cqa=function(a,b){g.ab(a,b)||a.push(b)},T5=function(a){var b=0,c;
for(c in a)b++;return b},U5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},dqa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},eqa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(dqa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},fqa=function(a,b,c,d){var e=new g.dn(null,void 0);
a&&g.en(e,a);b&&g.fn(e,b);c&&g.gn(e,c);d&&(e.i=d);return e},V5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return eqa(a)},W5=function(){this.g=[];
this.i=[]},X5=function(a,b){g.eq[a]=!0;
var c=g.cq();c&&c.publish.apply(c,arguments);g.eq[a]=!1},Y5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.an;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gqa(this,a.capabilities||""),hqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},gqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Ra(Vpa,iqa)).forEach(function(c){a.capabilities.add(c)})},hqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},Z5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},$5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},a6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},jqa=function(a){return new Z5(a)},b6=function(a){return g.La(a)?(0,g.G)(a,jqa):[]},c6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},d6=function(a){return g.La(a)?"["+(0,g.G)(a,c6).join(",")+"]":"null"},e6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},kqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},f6=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},g6=function(a,b){return g.Ya(a,function(c){return $5(c,b)})},lqa=function(){var a=(0,g.vt)();
a&&bqa(a,a.g.jf(!0))},h6=function(){var a=g.zt("yt-remote-connected-devices")||[];
g.qb(a);return a},mqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},i6=function(a){g.xt("yt-remote-connected-devices",a,86400)},k6=function(){if(j6)return j6;
var a=g.zt("yt-remote-device-id");a||(a=e6(),g.xt("yt-remote-device-id",a,31536E3));for(var b=h6(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return j6=d},l6=function(){var a=h6(),b=k6();
g.ab(a,b);g.Bt()&&g.sb(a,b);a=mqa(a);if(0==a.length)try{g.zs("remote_sid")}catch(c){}else try{g.ys("remote_sid",a.join(","),-1)}catch(c){}},m6=function(){return g.zt("yt-remote-session-browser-channel")},n6=function(){return g.zt("yt-remote-local-screens")||[]},o6=function(){g.xt("yt-remote-lounge-token-expiration",!0,86400)},nqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(n6(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.lj)(c,function(d){return!g.ab(b,d)})&&o6();
g.xt("yt-remote-local-screens",a,31536E3)},oqa=function(a,b){g.xt("yt-remote-session-browser-channel",a);
g.xt("yt-remote-session-screen-id",b);var c=h6(),d=k6();g.ab(c,d)||c.push(d);i6(c);l6()},p6=function(a){a||(g.At("yt-remote-session-screen-id"),g.At("yt-remote-session-video-id"));
l6();a=h6();g.db(a,k6());i6(a)},r6=function(){if(!q6){var a=g.jp();
a&&(q6=new g.Uo(a))}return q6?!!q6.get("yt-remote-use-staging-server"):!1},s6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},t6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},v6=function(a){a.length?u6(a.shift(),function(){v6(a)}):w6()},pqa=function(a){return"chrome-extension://"+a+x6},u6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},w6=function(){var a=t6();
a&&a(!1,"No cast extension found")},y6=function(){if(qqa){var a=2,b=t6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;u6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",w6,c)}},rqa=function(){y6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);v6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+x6,"//www.gstatic.com/eureka/clank"+x6])},z6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Vc=b;this.u=(0,g.y)(this.hD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},A6=function(){},B6=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.sn(this);this.i=new g.Hg;this.i.setInterval(250)},D6=function(a,b,c){a.ci=1;
a.lg=G5(b.clone());a.uh=c;a.u=!0;C6(a,null)},E6=function(a,b,c,d,e){a.ci=1;
a.lg=G5(b.clone());a.uh=null;a.u=c;e&&(a.cA=!1);C6(a,d)},C6=function(a,b){a.Ii=(0,g.C)();
F6(a);a.Dg=a.lg.clone();H5(a.Dg,"t",a.A);a.Zk=0;a.tc=a.g.wp(a.g.Qk()?b:null);0<a.bq&&(a.Bn=new g.Ml((0,g.y)(a.iB,a,a.tc),a.bq));a.aa.ca(a.tc,"readystatechange",a.YL);var c=a.Yg?g.bc(a.Yg):{};a.uh?(a.ko="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Dg,a.ko,a.uh,c)):(a.ko="GET",a.cA&&!g.Od&&(c.Connection="close"),a.tc.send(a.Dg,a.ko,null,c));a.g.re(1)},M6=function(a,b,c){for(var d=!0;!a.Og&&a.Zk<c.length;){var e=sqa(a,c);
if(e==G6){4==b&&(a.mg=4,H6(15),d=!1);break}else if(e==I6){a.mg=4;H6(16);d=!1;break}else J6(a,e)}4==b&&0==c.length&&(a.mg=1,H6(17),d=!1);a.xe=a.xe&&d;d||(K6(a),L6(a))},sqa=function(a,b){var c=a.Zk,d=b.indexOf("\n",c);
if(-1==d)return G6;c=Number(b.substring(c,d));if(isNaN(c))return I6;d+=1;if(d+c>b.length)return G6;var e=b.substr(d,c);a.Zk=d+c;return e},P6=function(a,b){a.Ii=(0,g.C)();
F6(a);var c=b?window.location.hostname:"";a.Dg=a.lg.clone();g.mn(a.Dg,"DOMAIN",c);g.mn(a.Dg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){K6(a);a.mg=7;H6(22);L6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in N6)k=N6[l];else if(l in O6)k=N6[l]=O6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
N6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Mc(c));a.Be.close();a.Be.parentWindow.m=(0,g.y)(a.pL,a);a.Be.parentWindow.d=(0,g.y)(a.hz,a,!0);a.Be.parentWindow.rpcClose=(0,g.y)(a.hz,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Cc(a.Dg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.re(1)},F6=function(a){a.kt=(0,g.C)()+a.o;
Q6(a,a.o)},Q6=function(a,b){if(null!=a.Zi)throw Error("WatchDog timer not null");
a.Zi=R6((0,g.y)(a.zL,a),b)},S6=function(a){a.Zi&&(g.w.clearTimeout(a.Zi),a.Zi=null)},L6=function(a){a.g.gw()||a.Og||a.g.ln(a)},K6=function(a){S6(a);
g.pf(a.Bn);a.Bn=null;a.i.stop();g.un(a.aa);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},J6=function(a,b){try{a.g.bz(a,b),a.g.re(4)}catch(c){}},U6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;T6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){U6(a,b,c,d,f)},f)})}},T6=function(a,b,c){var d=new Image;
d.onload=function(){try{V6(d),c(!0)}catch(e){}};
d.onerror=function(){try{V6(d),c(!1)}catch(e){}};
d.onabort=function(){try{V6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{V6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
U5(d,a)},V6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},W6=function(a){this.g=a;
this.i=new A6},Y6=function(a){var b=X6(a.g,a.jj,"/mail/images/cleardot.gif");
G5(b);U6(b.toString(),5E3,(0,g.y)(a.pC,a),3,2E3);a.re(1)},$6=function(a){var b=a.g.F;
if(null!=b)H6(5),b?(H6(11),Z6(a.g,a,!1)):(H6(12),Z6(a.g,a,!0));else if(a.Dd=new B6(a,void 0,void 0,void 0),a.Dd.Yg=a.Yp,b=a.g,b=X6(b,b.Qk()?a.Pj:null,a.Zp),H6(5),!g.Md||g.od(10))H5(b,"TYPE","xmlhttp"),E6(a.Dd,b,!1,a.Pj,!1);else{H5(b,"TYPE","html");var c=a.Dd;a=!!a.Pj;c.ci=3;c.lg=G5(b.clone());P6(c,a)}},a7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new A6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},tqa=function(a,b){this.g=a;
this.map=b;this.context=null},b7=function(a){g.rf.call(this,"statevent",a)},c7=function(a,b){g.rf.call(this,"timingevent",a);
this.size=b},d7=function(a){g.rf.call(this,"serverreachability",a)},h7=function(a){e7(a);
if(3==a.g){var b=a.yk++,c=a.Yl.clone();g.mn(c,"SID",a.l);g.mn(c,"RID",b);g.mn(c,"TYPE","terminate");f7(a,c);b=new B6(a,a.l,b,void 0);b.ci=2;b.lg=G5(c.clone());U5(new Image,b.lg.toString());b.Ii=(0,g.C)();F6(b)}g7(a)},j7=function(a){a.FC(1,0);
a.Yl=X6(a,null,a.Xp);i7(a)},e7=function(a){a.cg&&(a.cg.abort(),a.cg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.lf&&(g.w.clearTimeout(a.lf),a.lf=null);k7(a);a.Ad&&(a.Ad.cancel(),a.Ad=null);a.hg&&(g.w.clearTimeout(a.hg),a.hg=null)},l7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new tqa(a.DH++,b));2!=a.g&&3!=a.g||i7(a)},i7=function(a){a.Ad||a.hg||(a.hg=R6((0,g.y)(a.gz,a),0),a.Wh=0)},o7=function(a,b){if(1==a.g){if(!b){a.yk=Math.floor(1E5*Math.random());
var c=a.yk++,d=new B6(a,"",c,void 0);d.Yg=null;var e=m7(a),f=a.Yl.clone();g.mn(f,"RID",c);g.mn(f,"CVER","1");f7(a,f);D6(d,f,e);a.Ad=d;a.g=2}}else 3==a.g&&(b?n7(a,b):0==a.i.length||a.Ad||n7(a))},n7=function(a,b){if(b)if(6<a.Pg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.yk-1;var d=m7(a)}else c=b.C,d=b.uh;else c=a.yk++,d=m7(a);var e=a.Yl.clone();g.mn(e,"SID",a.l);g.mn(e,"RID",c);g.mn(e,"AID",a.ni);f7(a,e);c=new B6(a,a.l,c,a.Wh+1);c.Yg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ad=c;D6(c,e,d)},f7=function(a,b){if(a.Tc){var c=a.Tc.Iv();
c&&g.Kb(c,function(d,e){g.mn(b,e,d)})}},m7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Pg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Pg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},p7=function(a){a.Sb||a.lf||(a.C=1,a.lf=R6((0,g.y)(a.fz,a),0),a.Oh=0)},r7=function(a){if(a.Sb||a.lf||3<=a.Oh)return!1;
a.C++;a.lf=R6((0,g.y)(a.fz,a),q7(a,a.Oh));a.Oh++;return!0},Z6=function(a,b,c){a.ho=c;
a.Je=b.yf;a.A||j7(a)},k7=function(a){null!=a.Tg&&(g.w.clearTimeout(a.Tg),a.Tg=null)},q7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},t7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.EM,a);c||(c=new g.dn("//www.google.com/images/cleardot.gif"),G5(c));T6(c.toString(),1E4,d)}else H6(2);s7(a,b)},s7=function(a,b){a.g=0;
a.Tc&&a.Tc.Fu(b);g7(a);e7(a)},g7=function(a){a.g=0;
a.Je=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.ip();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Tc.ip(b)}},X6=function(a,b,c){var d=g.nn(c);
if(""!=d.g)b&&g.fn(d,b+"."+d.g),g.gn(d,d.u);else{var e=window.location;d=fqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.wj&&g.Kb(a.wj,function(f,k){g.mn(d,k,f)});
g.mn(d,"VER",a.Pg);f7(a,d);return d},R6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},H6=function(a){u7.dispatchEvent(new b7(u7,a))},uqa=function(){},vqa=function(a,b){this.action=a;
this.params=b||{}},v7=function(a,b){g.H.call(this);
this.g=new g.N(this.hL,0,this);g.I(this,this.g);this.Vc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},w7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.To;this.i=new v7(this.hM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},wqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ho,sessionId:a.g.l,arrayId:a.g.ni}},xqa=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&o7(a.g),h7(a.g));a.D=0},x7=function(a){return!!a.g&&3==a.g.g},yqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},y7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Vg(a)||"";b&&(this.port=":"+b);this.domain=g.Ug(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},z7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.dh(c+b,{})},A7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),qd:g.Ra(a.u,e)};c&&(a.qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Xq(b,a)},Cqa=function(){var a=zqa;
Aqa();B7.push(a);Bqa(B7)},C7=function(a,b){Aqa();
var c=B7,d=Dqa(a,String(b));0==c.length?Eqa(d):(Bqa(c),(0,g.B)(c,function(e){e(d)}))},Aqa=function(){B7||(B7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",B7,void 0))},Eqa=function(a){var b=(D7+1)%50;
D7=b;E7[b]=a;F7||(F7=49==b)},Bqa=function(a){var b=E7;
if(b[0]){var c=D7,d=F7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
E7=Array(50);D7=-1;F7=!1}},Dqa=function(a,b){var c=((0,g.C)()-Fqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},G7=function(a){g.Q.call(this);
this.C=a;this.g=[]},Gqa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Hqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!f6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Gqa(a,b[d])||c;return c},Iqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},H7=function(a,b,c,d){g.Q.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},J7=function(a){G7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;I7(this);this.info("Initializing with "+d6(this.g))},Jqa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=z7(a.l,"/pairing/get_lounge_token_batch");
A7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.rD,a),(0,g.y)(a.qD,a))}},I7=function(a){var b=b6(n6());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Hqa(a,b)},K7=function(a,b){nqa((0,g.G)(a.g,a6));
b&&o6()},M7=function(a,b){g.Q.call(this);
this.A=b;var c=g.zt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;L7("Initialized with "+g.Mg(this.g))},Kqa=function(a,b,c){var d=z7(a.u,"/pairing/get_screen_availability");
A7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},N7=function(a,b){a:if(T5(b)!=T5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(L7("Updated online screens: "+g.Mg(a.g)),a.g=b,a.N("screenChange"));Lqa(a)},O7=function(a){isNaN(a.l)||g.bq(a.l);
a.l=g.$p((0,g.y)(a.ks,a),0<a.o&&a.o<(0,g.C)()?2E4:1E4)},L7=function(a){C7("OnlineScreenService",a)},Mqa=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},Lqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.xt("yt-remote-online-screen-ids",a.join(","),60):g.At("yt-remote-online-screen-ids")},P7=function(a){G7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Nqa(this)},Pqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Jd();if(k=(c?g6(k,c):null)||g6(k,b)){k.uuid=b;var l=Q7(a,k);Kqa(a.i,l,function(m){e(m?l:null)})}else c?Oqa(a,c,(0,g.y)(function(m){var n=Q7(this,new Z5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Kqa(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},Qqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Oqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Xq(z7(a.A,"/pairing/get_lounge_token_batch"),e)},Rqa=function(a){a.g=a.l.Jd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+d6(a.g))},Nqa=function(a){R7(a);
a.l=new J7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.AD,a));Rqa(a);a.o=b6(g.zt("yt-remote-automatic-screen-cache")||[]);R7(a);a.info("Initializing automatic screens: "+d6(a.o));a.i=new M7(a.A,(0,g.y)(a.Jd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},Q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=g6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.xt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,a6)));R7(a);a.u[b.uuid]=b.id;g.xt("yt-remote-device-id-map",a.u,31536E3);return b},R7=function(a){a.u=g.zt("yt-remote-device-id-map")||{}},S7=function(a,b,c){g.Q.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},T7=function(a,b){C7(a.P,b)},U7=function(a,b){S7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.hN,this);this.u=(0,g.y)(this.KL,this);this.o=g.$p((0,g.y)(function(){Sqa(this,null)},this),12E4)},Tqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Mg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){T7(this,"Failed to send message: getMdxSessionStatus.")},a)):T7(a,"Sending yt message without session: "+g.Mg(b))},Sqa=function(a,b){g.bq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.mn,a),d=(0,g.y)(a.Nd,a);a.Yv(b,c,d,5)}}else a.Nd(Error("Waiting for session status timed out."))},V7=function(a,b,c){S7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ha;this.A=NaN;this.I=(0,g.y)(this.kN,this);this.g=g.Ha},Uqa=function(a){a.g=a.F.nB(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.mn(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Nd(b)},a))},Vqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}r6()&&(b.env_useStageMdx=1);return g.bh(b)},W7=function(a,b){S7.call(this,a,b,"ManualSession");
this.g=g.$p((0,g.y)(this.pi,this,null),150)},X7=function(a,b,c,d){g.Q.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.qK,this)},Wqa=function(a,b){return b?g.Ya(a.l,function(c){return $5(b,c.label)},a):null},Y7=function(a){C7("Controller",a)},zqa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},Z7=function(a){return a.u||!!a.l.length||!!a.g},$7=function(a,b,c){b!=a.g&&(g.pf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.ez,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.pi(null)):a.N("yt-remote-cast2-session-change",null))},Xqa=function(a){var b=a.i.mB(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&$5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Wqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},cra=function(a,b,c,d,e,f,k){Yqa()?Zqa(b,e,f,k)&&(b8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?$qa(a,c):(window.__onGCastApiAvailable=function(l,m){l?$qa(a,c):(c8("Failed to load cast API: "+m),d8(!1),b8(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),ara(),c(!1))},d?g.mq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?rqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?w6():(y6(),v6(bra.map(pqa))))):a8("Cannot initialize because not running Chrome")},ara=function(){a8("dispose");
var a=e8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);dra(!1);g.hq(f8);f8.length=0},g8=function(){return!!g.zt("yt-remote-cast-installed")},era=function(){var a=g.zt("yt-remote-cast-receiver");
return a?a.friendlyName:null},fra=function(){a8("clearCurrentReceiver");
g.At("yt-remote-cast-receiver")},gra=function(){return g8()?e8()?e8().getCastSession():(c8("getCastSelector: Cast is not initialized."),null):(c8("getCastSelector: Cast API is not installed!"),null)},i8=function(){g8()?e8()?h8()?(a8("Requesting cast selector."),e8().requestSession()):(a8("Wait for cast API to be ready to request the session."),f8.push(g.gq("yt-remote-cast2-api-ready",i8))):c8("requestCastSelector: Cast is not initialized."):c8("requestCastSelector: Cast API is not installed!")},j8=
function(a,b){h8()?e8().setConnectedScreenStatus(a,b):c8("setConnectedScreenStatus called before ready.")},Yqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.gx||a},hra=function(a,b){e8().init(a,b)},Zqa=function(a,b,c,d){var e=!1;
e8()||(a=new X7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.xt("yt-remote-cast-available",f);X5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){a8("onReceiverSelected: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f);X5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){a8("onReceiverResumed: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){a8("onSessionChange: "+c6(f));
f||g.At("yt-remote-cast-receiver");X5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
a8("cloudview.createSingleton_: "+e);return e},e8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},$qa=function(a,b){d8(!0);
b8(!1);hra(a,function(c){c?(dra(!0),g.jq("yt-remote-cast2-api-ready")):(c8("Failed to initialize cast API."),d8(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),ara());b(c)})},a8=function(a){C7("cloudview",a)},c8=function(a){C7("cloudview",a)},d8=function(a){a8("setCastInstalled_ "+a);
g.xt("yt-remote-cast-installed",a)},h8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},dra=function(a){a8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},b8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},k8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Le=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},l8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Le=!1;a.hasNext=!1;a.C=0;a.A=(0,g.C)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},m8=function(a){return 1==a.playerState?((0,g.C)()-a.A)/1E3:0},n8=function(a,b){a.C=b;
a.A=(0,g.C)()},o8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},p8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&l8(a)},q8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Le;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},s8=function(a,b){g.Q.call(this);
this.g=0;this.o=a;this.A=[];this.u=new W5;this.l=this.i=null;this.F=(0,g.y)(this.kI,this);this.C=(0,g.y)(this.Bk,this);this.D=(0,g.y)(this.jI,this);this.H=(0,g.y)(this.wI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.nt,this),ira(this))):c=3;0!=c&&(b?this.nt(c):g.$p((0,g.y)(function(){this.nt(c)},this),0));
var d=gra();d&&r8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},t8=function(a){return new k8(a.o.getPlayerContextData())},ira=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Ra(this.nK,b),this))},a)},jra=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},u8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},w8=function(a,b,c){var d=t8(a);
n8(d,c);-1E3!=d.playerState&&(d.playerState=b);v8(a,d)},x8=function(a,b,c){a.o.sendMessage(b,c)},v8=function(a,b){jra(a);
a.o.setPlayerContextData(q8(b));ira(a)},r8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Bk(null));
a.l=b;a.l&&(C7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Bk(a.l.media[0]))},kra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=t8(a);b.contentId!=d.videoId&&C7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;n8(d,a.i.getEstimatedTime());v8(a,d)}else C7("CP","No cast media video. Ignoring state update.")},y8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),x8(this,b,c))},a)},z8=function(a,b,c){g.Q.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.O=a;this.P.push(g.ds(window,"beforeunload",(0,g.y)(this.kD,this)));this.i=[];this.Oa=new k8;this.M=b.id;this.g=lra(this,c);this.g.subscribe("handlerOpened",this.oI,this);this.g.subscribe("handlerClosed",this.lI,this);this.g.subscribe("handlerError",this.mI,this);this.g.subscribe("handlerMessage",this.nI,this);yqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.Bt()&&g.xt("yt-remote-session-video-id",d)},this)},A8=function(a){C7("conn",a)},lra=function(a,b){return new w7(z7(a.O,"/bc"),b)},B8=function(a,b){a.N("proxyStateChange",b)},mra=function(a){a.u=g.$p((0,g.y)(function(){A8("Connecting timeout");
this.Sh(1)},a),2E4)},C8=function(a){g.bq(a.u);
a.u=NaN},D8=function(a){g.bq(a.H);
a.H=NaN},nra=function(a){E8(a);
a.F=g.$p((0,g.y)(function(){F8(this,"getNowPlaying")},a),2E4)},E8=function(a){g.bq(a.F);
a.F=NaN},pra=function(a,b){b&&(C8(a),D8(a));
b==(x7(a.g)&&isNaN(a.u))?b&&(B8(a,1),F8(a,"getSubtitlesTrack")):b?(a.Vv()&&a.Oa.reset(),B8(a,1),F8(a,"getNowPlaying"),ora(a)):a.Sh(1)},qra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Xb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},rra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;p8(a.Oa,c,d);a.N("remoteQueueChange")},tra=function(a,b){b.params=b.params||{};
rra(a,b);sra(a,b);a.N("autoplayDismissed")},sra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
n8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?nra(a):E8(a);a.N("remotePlayerChange")},ura=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);n8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},vra=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},wra=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},xra=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Le="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},ora=function(a){g.bq(a.D);
a.D=g.$p((0,g.y)(a.Sh,a,1),864E5)},F8=function(a,b,c){c?A8("Sending: action="+b+", params="+g.Mg(c)):A8("Sending: action="+b);
a.g.sendMessage(b,c)},G8=function(a){G7.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.y)(this.fN,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.y)(this.RJ,this)))},Cra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Sp("MDX_CONFIG")||b;lqa();l6();H8||(H8=new y7(b?b.loungeApiHost:void 0),r6()&&(H8.g="/api/loungedev"));I8||(I8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",I8,void 0));yra();var c=J8();if(!c){var d=new P7(H8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=J8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);cra(a,d,function(m){m?K8()&&j8(K8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){X5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),L8("Initializing: "+g.Mg(b)),M8.push(g.gq("yt-remote-cast2-availability-change",function(){X5("yt-remote-receiver-availability-change")})),M8.push(g.gq("yt-remote-cast2-receiver-selected",function(){N8(null);
X5("yt-remote-auto-connect","cast-selector-receiver")})),M8.push(g.gq("yt-remote-cast2-receiver-resumed",function(){X5("yt-remote-receiver-resumed","cast-selector-receiver")})),M8.push(g.gq("yt-remote-cast2-session-change",zra)),M8.push(g.gq("yt-remote-connection-change",function(m){m?j8(K8(),"YouTube TV"):O8()||(j8(null,null),fra())})),a=P8(),b.isAuto&&(a.id+="#dial"),g.Oq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),L8(" -- with channel params: "+
g.Mg(a)),Ara(a),c.start(),K8()||Bra())},Era=function(){var a=Dra();
g8()&&g.zt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Dra=function(){var a=J8().Hc.$_gos();
var b=Q8();b&&R8()&&(f6(a,b)||a.push(b));return kqa(a)},S8=function(){var a=Fra();
!a&&g8()&&era()&&(a={key:"cast-selector-receiver",name:era()});return a},Fra=function(){var a=Dra(),b=Q8();
b||(b=O8());return g.Ya(a,function(c){return b&&$5(b,c.key)?!0:!1})},Q8=function(){var a=K8();
if(!a)return null;var b=J8().Jd();return g6(b,a)},zra=function(a){L8("remote.onCastSessionChange_: "+c6(a));
if(a){var b=Q8();b&&b.id==a.id?j8(b.id,"YouTube TV"):(b&&T8(),U8(a,1))}else R8()&&T8()},T8=function(){h8()?e8().stopSession():c8("stopSession called before API ready.");
var a=R8();a&&(a.disconnect(1),V8(null))},W8=function(){var a=R8();
return!!a&&3!=a.getProxyState()},L8=function(a){C7("remote",a)},J8=function(){if(!X8){var a=g.x("yt.mdx.remote.screenService_");
X8=a?new G8(a):null}return X8},K8=function(){return g.x("yt.mdx.remote.currentScreenId_")},Gra=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Hra=function(){return g.x("yt.mdx.remote.connectData_")},N8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},R8=function(){return g.x("yt.mdx.remote.connection_")},V8=function(a){var b=R8();
N8(null);a||Gra("");g.Ga("yt.mdx.remote.connection_",a,void 0);I8&&((0,g.B)(I8,function(c){c(a)}),I8.length=0);
b&&!a?X5("yt-remote-connection-change",!1):!b&&a&&X5("yt-remote-connection-change",!0)},O8=function(){var a=g.Bt();
if(!a)return null;var b=J8().Jd();return g6(b,a)},U8=function(a,b){Q8()&&Q8();
if(Y8)Z8=a;else{Gra(a.id);var c=new z8(H8,a,P8());c.connect(b,Hra());c.subscribe("beforeDisconnect",function(d){X5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){R8()&&V8(null)});
V8(c)}},Bra=function(){var a=O8();
a?(L8("Resume connection to: "+c6(a)),U8(a,0)):(p6(),fra(),L8("Skipping connecting because no session screen found."))},yra=function(){var a=P8();
if(g.Xb(a)){a=k6();var b=g.zt("yt-remote-session-name")||"",c=g.zt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},P8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Ara=function(a){a?(g.xt("yt-remote-session-app",a.app),g.xt("yt-remote-session-name",a.name)):(g.At("yt-remote-session-app"),g.At("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},$8=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.Ms(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.kJ);this.l.K(b,"captionschanged",this.iI);this.l.K(b,"captionssettingschanged",this.BA);this.l.K(b,"videoplayerreset",this.nn);this.l.K(b,"mdxautoplaycancel",this.oC);this.O=this.l.K(b,"onVolumeChange",this.Py);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.az,this);c.subscribe("remotePlayerChange",this.Dk,this);c.subscribe("remoteQueueChange",this.nn,this);c.subscribe("autoplayUpNext",this.Ey,
this);c.subscribe("previousNextChange",this.Xy,this);c.subscribe("nowAutoplaying",this.Ty,this);c.subscribe("autoplayDismissed",this.Dy,this);this.suggestion=null;this.F=new g.CC(64);this.o=new g.N(this.zA,500,this);g.I(this,this.o);this.A=new g.N(this.AA,1E3,this);g.I(this,this.A);this.I=new z6(this.OM,0,this);g.I(this,this.I);this.C={};this.P=new g.N(this.ZA,1E3,this);g.I(this,this.P);this.H=new g.Ml(this.IF,1E3,this);g.I(this,this.H);this.M=g.Ha;this.BA();this.nn();this.Dk()},a9=function(a,b){a.u.sd(b,
a.i.getVideoData().lengthSeconds)},Ira=function(a){a9(a,0);
a.o.stop();b9(a,new g.CC(64))},d9=function(a,b){if(c9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.pA(a.i.getVideoData(1).videoId,c);a.C=t8(a.g).g}},e9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ra;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Af,S5(c));b9(a,new g.CC(1))},Jra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{zQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},c9=function(a){return t8(a.g).videoId==a.i.getVideoData(1).videoId},b9=function(a,b){a.A.stop();
var c=a.F;if(!g.IC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.wK(a.i,d);a.F=b;Kra(a.u,c,b)}},f9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"\u60a8\u5df2\u9000\u51fa\u5e10\u53f7"},{B:"div",G:"ytp-mdx-popup-description",U:"\u60a8\u89c2\u770b\u7684\u89c6\u9891\u53ef\u80fd\u4f1a\u6dfb\u52a0\u5230\u7535\u89c6\u7684\u89c2\u770b\u8bb0\u5f55\u4e2d\uff0c\u5e76\u5f71\u54cd\u7535\u89c6\u4e0a\u7684\u63a8\u8350\u5185\u5bb9\u3002\u4e3a\u907f\u514d\u53d1\u751f\u8fd9\u79cd\u60c5\u51b5\uff0c\u8bf7\u53d6\u6d88\u5e76\u5728\u8ba1\u7b97\u673a\u4e0a\u767b\u5f55 YouTube\u3002"},
{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"\u53d6\u6d88"},{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],U:"\u786e\u8ba4"}]}]}]});this.l=new g.rQ(this,250);g.I(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},g9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.HP()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.rQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);Lra(this,g.sK(a))},Lra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.FN("\u5728$RECEIVER_NAME\u4e0a\u51fa\u73b0\u9519\u8bef",c):g.JC(b)||g.U(b,4)?g.FN("\u6b63\u5728$RECEIVER_NAME\u4e0a\u64ad\u653e",c):g.FN("\u5df2\u8fde\u63a5\u5230$RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.cU.call(this,"\u64ad\u653e\u8bbe\u5907",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.VK.call(this,a);
this.i={key:e6(),name:"\u6b64\u8ba1\u7b97\u673a"};this.u=null;this.l=[];this.C=this.g=null;this.A=[this.i];this.o=this.i;this.jk=new g.CC(64);this.H=0;this.Em=-1;if(!g.lz(g.X(this.player))){a=this.player;var b=g.vD(a);b&&(b=b.lk())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.HK(a,b.element,4);this.F=new f9;g.I(this,this.F);g.HK(a,this.F.element,4);this.D=!!O8()}},Kra=function(a,b,c){a.jk=c;
a.player.N("presentingplayerstatechange",new g.JD(c,b))},j9=function(a,b){if(b.key!=a.o.key)if(b.key==a.i.key)T8();
else{var c;if(c=g.R(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.Sp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Sp("SESSION_INDEX")||g.Sp("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),R8()||(Y8=!0));a.o=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Af,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=S5(c))&&(d.locationInfo=c);c=d}else c=null;L8("Connecting to: "+g.Mg(b));"cast-selector-receiver"==b.key?(N8(c||null),h8()?e8().setLaunchParams(c||null):c8("setLaunchParams called before ready.")):!c&&W8()&&K8()==b.key?X5("yt-remote-connection-change",!0):(T8(),N8(c||null),c=J8().Jd(),(c=g6(c,b.key))&&U8(c,1))}},$pa=/^https?$/i,Mra=["POST",
"PUT"];g.A(Q5,g.Sf);g.h=Q5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?I5(this.M):I5(g.bZ);this.P=this.M?this.M.getOptions():g.bZ.getOptions();this.g.onreadystatechange=(0,g.y)(this.iw,this);try{F5(J5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){F5(J5(this,"Error opening Xhr: "+f.message));N5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Xpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Hd(),Ypa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(Mra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{K5(this),0<this.A&&(this.I=Zpa(this.g),F5(J5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.jw,this)):this.C=g.Ig(this.jw,this.A,this)),F5(J5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){F5(J5(this,"Send error: "+f.message)),N5(this,f)}};
g.h.jw=function(){"undefined"!=typeof g.GY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,J5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(J5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),M5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),M5(this,!0));Q5.Ua.T.call(this)};
g.h.iw=function(){this.da()||(this.V||this.D||this.o?P5(this):this.pK())};
g.h.pK=function(){P5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<O5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var O6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},N6={"'":"\\'"},Nra={};g.h=W5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Kma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var iqa={DN:"atp",NP:"ska",CP:"que",cP:"mus",MP:"sus",tO:"dsp",JP:"seq"};Y5.prototype.dg=function(){var a=new Y5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var q6,j6="",x6=s6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",qqa=s6("loadCastFramework")||s6("loadCastApplicationFramework"),bra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(z6,g.H);g.h=z6.prototype;g.h.gD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.C)()+this.Vc:this.za=g.Ig(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();z6.Ua.T.call(this)};
g.h.hD=function(){this.l?(this.za=g.Ig(this.u,this.l-(0,g.C)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};A6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
A6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=B6.prototype;g.h.Yg=null;g.h.xe=!1;g.h.Zi=null;g.h.kt=null;g.h.Ii=null;g.h.ci=null;g.h.lg=null;g.h.Dg=null;g.h.uh=null;g.h.tc=null;g.h.Zk=0;g.h.Be=null;g.h.ko=null;g.h.mg=null;g.h.Qj=-1;g.h.cA=!0;g.h.Og=!1;g.h.bq=0;g.h.Bn=null;var I6={},G6={};g.h=B6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.YL=function(a){a=a.target;var b=this.Bn;b&&3==O5(a)?b.Mj():this.iB(a)};
g.h.iB=function(a){try{if(a==this.tc)a:{var b=O5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Md&&!g.od(10)||g.Od&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Dh&&!R5(this.tc))break a;this.Og||4!=b||7==c||(8==c||0>=d?this.g.re(3):this.g.re(2));S6(this);var e=this.tc.getStatus();this.Qj=e;var f=R5(this.tc);(this.xe=200==e)?(4==b&&K6(this),this.u?(M6(this,b,f),g.Dh&&this.xe&&3==b&&(this.aa.ca(this.i,"tick",this.SL),this.i.start())):J6(this,f),this.xe&&!this.Og&&(4==b?this.g.ln(this):(this.xe=
!1,F6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mg=3,H6(13)):(this.mg=0,H6(14)),K6(this),L6(this))}}catch(k){this.tc&&R5(this.tc)}finally{}};
g.h.SL=function(){var a=O5(this.tc),b=R5(this.tc);this.Zk<b.length&&(S6(this),M6(this,a,b),this.xe&&4!=a&&F6(this))};
g.h.pL=function(a){R6((0,g.y)(this.oL,this,a),0)};
g.h.oL=function(a){this.Og||(S6(this),J6(this,a),F6(this))};
g.h.hz=function(a){R6((0,g.y)(this.nL,this,a),0)};
g.h.nL=function(a){this.Og||(K6(this),this.xe=a,this.g.ln(this),this.g.re(4))};
g.h.cancel=function(){this.Og=!0;K6(this)};
g.h.zL=function(){this.Zi=null;var a=(0,g.C)();0<=a-this.kt?(2!=this.ci&&this.g.re(3),K6(this),this.mg=2,H6(18),L6(this)):Q6(this,this.kt-a)};
g.h.getLastError=function(){return this.mg};g.h=W6.prototype;g.h.Yp=null;g.h.Dd=null;g.h.Cn=!1;g.h.hw=null;g.h.Wl=null;g.h.Mq=null;g.h.Zp=null;g.h.ce=null;g.h.yf=-1;g.h.Pj=null;g.h.jj=null;g.h.connect=function(a){this.Zp=a;a=X6(this.g,null,this.Zp);H6(3);this.hw=(0,g.C)();var b=this.g.D;null!=b?(this.Pj=b[0],(this.jj=b[1])?(this.ce=1,Y6(this)):(this.ce=2,$6(this))):(H5(a,"MODE","init"),this.Dd=new B6(this,void 0,void 0,void 0),this.Dd.Yg=this.Yp,E6(this.Dd,a,!1,null,!0),this.ce=0)};
g.h.pC=function(a){if(a)this.ce=2,$6(this);else{H6(4);var b=this.g;b.Je=b.cg.yf;t7(b,9)}a&&this.re(2)};
g.h.wp=function(a){return this.g.wp(a)};
g.h.abort=function(){this.Dd&&(this.Dd.cancel(),this.Dd=null);this.yf=-1};
g.h.gw=function(){return!1};
g.h.bz=function(a,b){this.yf=a.Qj;if(0==this.ce)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.yf;t7(c,2);return}this.Pj=c[0];this.jj=c[1]}else c=this.g,c.Je=this.yf,t7(c,2);else if(2==this.ce)if(this.Cn)H6(7),this.Mq=(0,g.C)();else if("11111"==b){if(H6(6),this.Cn=!0,this.Wl=(0,g.C)(),c=this.Wl-this.hw,!g.Md||g.od(10)||500>c)this.yf=200,this.Dd.cancel(),H6(12),Z6(this.g,this,!0)}else H6(8),this.Wl=this.Mq=(0,g.C)(),this.Cn=!1};
g.h.ln=function(){this.yf=this.Dd.Qj;if(this.Dd.xe)0==this.ce?this.jj?(this.ce=1,Y6(this)):(this.ce=2,$6(this)):2==this.ce&&((!g.Md||g.od(10)?!this.Cn:200>this.Mq-this.Wl)?(H6(11),Z6(this.g,this,!1)):(H6(12),Z6(this.g,this,!0)));else{0==this.ce?H6(9):2==this.ce&&H6(10);var a=this.g;this.Dd.getLastError();a.Je=this.yf;t7(a,2)}};
g.h.Qk=function(){return this.g.Qk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.re=function(a){this.g.re(a)};g.h=a7.prototype;g.h.wj=null;g.h.Ad=null;g.h.Sb=null;g.h.Xp=null;g.h.Yl=null;g.h.xu=null;g.h.lm=null;g.h.yk=0;g.h.DH=0;g.h.Tc=null;g.h.hg=null;g.h.lf=null;g.h.Tg=null;g.h.cg=null;g.h.ho=null;g.h.ni=-1;g.h.Mw=-1;g.h.Je=-1;g.h.Wh=0;g.h.Oh=0;g.h.Pg=8;var u7=new g.Sf;g.A(b7,g.rf);g.A(c7,g.rf);g.A(d7,g.rf);g.h=a7.prototype;g.h.connect=function(a,b,c,d,e){H6(0);this.Xp=b;this.wj=c||{};d&&g.Da(e)&&(this.wj.OSID=d,this.wj.OAID=e);this.A?(R6((0,g.y)(this.Nu,this,a),100),j7(this)):this.Nu(a)};
g.h.Nu=function(a){this.cg=new W6(this);this.cg.Yp=null;this.cg.i=this.u;this.cg.connect(a)};
g.h.gw=function(){return 0==this.g};
g.h.gz=function(a){this.hg=null;o7(this,a)};
g.h.fz=function(){this.lf=null;this.Sb=new B6(this,this.l,"rpc",this.C);this.Sb.Yg=null;this.Sb.bq=0;var a=this.xu.clone();g.mn(a,"RID","rpc");g.mn(a,"SID",this.l);g.mn(a,"CI",this.ho?"0":"1");g.mn(a,"AID",this.ni);f7(this,a);if(!g.Md||g.od(10))g.mn(a,"TYPE","xmlhttp"),E6(this.Sb,a,!0,this.lm,!1);else{g.mn(a,"TYPE","html");var b=this.Sb,c=!!this.lm;b.ci=3;b.lg=G5(a.clone());P6(b,c)}};
g.h.bz=function(a,b){if(0!=this.g&&(this.Sb==a||this.Ad==a))if(this.Je=a.Qj,this.Ad==a&&3==this.g)if(7<this.Pg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.lf){if(this.Sb)if(this.Sb.Ii+3E3<this.Ad.Ii)k7(this),this.Sb.cancel(),this.Sb=null;else break a;r7(this);H6(19)}}else this.Mw=c[1],0<this.Mw-this.ni&&37500>c[2]&&this.ho&&0==this.Oh&&!this.Tg&&(this.Tg=R6((0,g.y)(this.eI,this),6E3));else t7(this,11)}else b!=Nra.YN.g&&t7(this,11);else if(this.Sb==a&&
k7(this),!g.wb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.ni=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.lm=e[2],e=e[3],null!=e?this.Pg=e:this.Pg=6,this.g=3,this.Tc&&this.Tc.Hu(),this.xu=X6(this,this.Qk()?this.lm:null,this.Xp),p7(this)):"stop"==e[0]&&t7(this,7):3==this.g&&("stop"==e[0]?t7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Gu(e),this.Oh=0)}}};
g.h.eI=function(){null!=this.Tg&&(this.Tg=null,this.Sb.cancel(),this.Sb=null,r7(this),H6(20))};
g.h.ln=function(a){if(this.Sb==a){k7(this);this.Sb=null;var b=2}else if(this.Ad==a)this.Ad=null,b=1;else return;this.Je=a.Qj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.C)()-a.Ii,u7.dispatchEvent(new c7(u7,a.uh?a.uh.length:0,b,this.Wh)),i7(this),this.o.length=0):p7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.Ad||this.hg||1==this.g||2<=this.Wh?d=!1:(this.hg=R6((0,g.y)(this.gz,this,a),q7(this,this.Wh)),this.Wh++,d=!0);d=!(d||2==b&&r7(this))}if(d)switch(c){case 1:t7(this,
5);break;case 4:t7(this,10);break;case 3:t7(this,6);break;case 7:t7(this,12);break;default:t7(this,2)}}};
g.h.FC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.EM=function(a){a?H6(2):(H6(1),s7(this,8))};
g.h.wp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.re=function(a){u7.dispatchEvent(new d7(u7,a))};
g.h.Qk=function(){return!(!g.Md||g.od(10))};
g.h=uqa.prototype;g.h.Hu=function(){};
g.h.Gu=function(){};
g.h.Fu=function(){};
g.h.ip=function(){};
g.h.Iv=function(){return{}};
g.h.isActive=function(){return!0};g.A(v7,g.H);g.h=v7.prototype;g.h.hL=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.uo(this.g,a);this.i=(0,g.C)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(w7,uqa);g.h=w7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Hf=function(a){return this.l.Zg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.pf(this.l),xqa(this),g.pf(this.i),this.i=null)};
g.h.da=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new a7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ni):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):x7(this)&&l7(this.g,c)};
g.h.Hu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)l7(this.g,a[b])}this.N("handlerOpened")};
g.h.Fu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.ip=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Iv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.Gu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),h7(this.g)):this.N("handlerMessage",new vqa(a[0],a[1]))};
g.h.hM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.Ad&&b++;0==b&&this.connect(this.u,this.o)};y7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
y7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
y7.prototype.u=function(a){a(Error("request timed out"))};var Fqa=(0,g.C)(),B7=null,E7=Array(50),D7=-1,F7=!1;g.A(G7,g.Q);G7.prototype.Jd=function(){return this.g};
G7.prototype.contains=function(a){return!!f6(this.g,a)};
G7.prototype.get=function(a){return a?g6(this.g,a):null};
G7.prototype.info=function(a){C7(this.C,a)};g.A(H7,g.Q);var Ora=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=H7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.lB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.bq(this.za),this.za=NaN)};
g.h.T=function(){this.stop();H7.Ua.T.call(this)};
g.h.lB=function(){this.za=NaN;this.g=g.Xq(z7(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.dN,this),onError:(0,g.y)(this.cN,this),qd:(0,g.y)(this.eN,this)})};
g.h.dN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new Z5(c))};
g.h.cN=function(a){this.g=null;a.status&&404==a.status?this.i>=Ora.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Ora[this.i],this.za=g.$p((0,g.y)(this.lB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.eN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(J7,G7);g.h=J7.prototype;g.h.start=function(){I7(this)&&this.N("screenChange");!g.zt("yt-remote-lounge-token-expiration")&&Jqa(this);g.bq(this.i);this.i=g.$p((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){I7(this);Gqa(this,a);K7(this,!1);this.N("screenChange");b(a);a.token||Jqa(this)};
g.h.remove=function(a,b){var c=I7(this);Iqa(this,a)&&(K7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.bo=function(a,b,c,d){var e=I7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,K7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.bq(this.i);J7.Ua.T.call(this)};
g.h.rD=function(a){I7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}K7(this,!b);b&&C7(this.C,"Missed "+b+" lounge tokens.")};
g.h.qD=function(a){C7(this.C,"Requesting lounge tokens failed: "+a)};g.A(M7,g.Q);g.h=M7.prototype;g.h.start=function(){var a=parseInt(g.zt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.C)()-144E5<a?0:a)?O7(this):(this.o=(0,g.C)()+3E5,g.xt("yt-remote-fast-check-period",this.o),this.ks())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){L7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!g6(a,d)},this);
N7(this,b)};
g.h.T=function(){g.bq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);M7.Ua.T.call(this)};
g.h.ks=function(){g.bq(this.l);this.l=NaN;this.i&&this.i.abort();var a=Mqa(this);if(T5(a)){var b=z7(this.u,"/pairing/get_screen_availability");this.i=A7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.y)(this.LK,this,a),(0,g.y)(this.KK,this))}else N7(this,{}),O7(this)};
g.h.LK=function(a,b){this.i=null;var c=g.Rb(Mqa(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;N7(this,d);O7(this)}else this.Jb("Changing Screen set during request."),this.ks()};
g.h.KK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;O7(this)};
g.h.Jb=function(a){C7("OnlineScreenService",a)};g.A(P7,G7);g.h=P7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.bo=function(a,b,c,d){this.l.contains(a)?this.l.bo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,C7(this.C,a),d(Error(a)))};
g.h.Jd=function(a){return a?this.g:g.fb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.mB=function(){return(0,g.Yd)(this.Jd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.nB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new H7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.pf(f);d(Q7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.pf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.gN=function(a,b,c,d){g.Xq(z7(this.A,"/pairing/get_screen"),{method:"POST",qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new Z5(f.screen||{});if(!k.name||Qqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Qqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(Q7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
qd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.pf(this.l);g.pf(this.i);P7.Ua.T.call(this)};
g.h.AD=function(){Rqa(this);this.N("screenChange");this.i.update()};
P7.prototype.dispose=P7.prototype.dispose;g.A(S7,g.Q);g.h=S7.prototype;g.h.mn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Nd=function(a){this.da()||(a&&T7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){C7(this.P,a)};
g.h.pB=function(){return null};
g.h.zs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){T7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.zs("");S7.Ua.T.call(this)};g.A(U7,S7);g.h=U7.prototype;g.h.ys=function(a){if(this.g){if(this.g==a)return;T7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Tqa(this)};
g.h.pi=function(a){this.info("launchWithParams no-op for Cast: "+g.Mg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Nd()},this),(0,g.y)(function(){this.Nd(Error("Failed to stop receiver app."))},this)):this.Nd(Error("Stopping cast device witout session."))};
g.h.zs=g.Ha;g.h.T=function(){this.info("disposeInternal");g.bq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;U7.Ua.T.call(this)};
g.h.KL=function(a,b){if(!this.da())if(b){var c=V5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Mg(c));switch(d){case "mdxSessionStatus":Sqa(this,c.screenId);break;default:T7(this,"Unknown youtube message: "+d)}}else T7(this,"Unable to parse message.")}else T7(this,"No data in message.")};
g.h.Yv=function(a,b,c,d){Pqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(T7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.$p((0,g.y)(this.Yv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.pB=function(){return this.g};
g.h.hN=function(a){this.da()||a||(T7(this,"Cast session died."),this.Nd())};g.A(V7,S7);g.h=V7.prototype;g.h.ys=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.pi=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ha;g.bq(this.A);this.o?this.o.stop((0,g.y)(this.Nd,this,null),(0,g.y)(this.Nd,this,"Failed to stop DIAL device.")):this.Nd()};
g.h.T=function(){this.g();this.g=g.Ha;g.bq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;V7.Ua.T.call(this)};
g.h.kN=function(a){this.da()||a||(T7(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Nd())};
g.h.oq=function(a){this.H=e6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Vqa(this));a(b);Uqa(this)}else this.C=(0,g.y)(function(){g.bq(this.A);this.C=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Vqa(this));a(c);Uqa(this)},this),this.A=g.$p((0,g.y)(function(){this.C()},this),100)};
g.h.YD=function(a,b,c){Pqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.mn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.oq(b,c)},this),(0,g.y)(function(d){T7(this,"Failed to get DIAL screen: "+d);
this.oq(b,c)},this))};g.A(W7,S7);W7.prototype.stop=function(){this.Nd()};
W7.prototype.ys=g.Ha;W7.prototype.pi=function(){g.bq(this.g);this.g=NaN;var a=g6(this.F.Jd(),this.i.label);a?this.mn(a):this.Nd(Error("No such screen"))};
W7.prototype.T=function(){g.bq(this.g);this.g=NaN;W7.Ua.T.call(this)};g.A(X7,g.Q);g.h=X7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.dz,this),(0,g.y)(this.uK,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.FI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),Cqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.oB,this)),this.l=Xqa(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Mg(f))},this)),this.N("yt-remote-cast2-availability-change",Z7(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Mg(f));
b(!1)},this))};
g.h.rM=function(a,b){Y7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)Y7("Unsetting old screen status: "+this.g.i.friendlyName),$7(this,null)}if(a&&b){if(!this.g){c=g6(this.i.Jd(),a);if(!c){Y7("setConnectedScreenStatus: Unknown screen.");return}var d=Wqa(this,c);d||(Y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Mg(e))},this)));
Y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);$7(this,new W7(this.i,d),!0)}this.g.zs(b)}else Y7("setConnectedScreenStatus: no screen.")};
g.h.sM=function(a){this.da()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.pi(a):this.Jb("Setting connection data without a session")};
g.h.jN=function(){this.da()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),$7(this,null)):Y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.dz,this),(0,g.y)(this.QK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.oB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],zqa);g.pf(this.g);X7.Ua.T.call(this)};
g.h.Jb=function(a){C7("Controller",a)};
g.h.ez=function(a,b){this.g==a&&(b||$7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.qK=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),Y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)Y7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{Y7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:$7(this,
new W7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:$7(this,new V7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:$7(this,new U7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.FI=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return Y7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);$7(this,new V7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.YD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.oq,b))};
g.h.dz=function(a){if(!this.da()){Y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)Y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),$7(this,new U7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=g6(this.i.Jd(),c.label);d&&$5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(Y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.pf(this.g),this.g=new U7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.ez,this,this.g)),this.g.pi(null));this.g.ys(a)}}};
g.h.iN=function(){return this.g?this.g.pB():null};
g.h.QK=function(a){this.da()||(this.Jb("Failed to estabilish a session: "+g.Mg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&$7(this,null))};
g.h.uK=function(a){Y7("Receiver availability updated: "+a);if(!this.da()){var b=Z7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;Z7(this)!=b&&this.N("yt-remote-cast2-availability-change",Z7(this))}};
g.h.oB=function(){this.da()||(this.l=Xqa(this),Y7("Updating custom receivers: "+g.Mg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",Z7(this)))};
X7.prototype.setLaunchParams=X7.prototype.sM;X7.prototype.setConnectedScreenStatus=X7.prototype.rM;X7.prototype.stopSession=X7.prototype.jN;X7.prototype.getCastSession=X7.prototype.iN;X7.prototype.requestSession=X7.prototype.requestSession;X7.prototype.init=X7.prototype.init;X7.prototype.dispose=X7.prototype.dispose;var f8=[];k8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";l8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Le=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
k8.prototype.isAdPlaying=function(){return 1081==this.playerState};
k8.prototype.getDuration=function(){return this.u?this.D+m8(this):this.D};
k8.prototype.clone=function(){return new k8(q8(this))};g.t(s8,g.Q);g.h=s8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,y8(this,"play")):x8(this,"play"),w8(this,1,o8(t8(this))),this.N("remotePlayerChange")):u8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,y8(this,"pause")):x8(this,"pause"),w8(this,2,o8(t8(this))),this.N("remotePlayerChange")):u8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=t8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,y8(this,"seekTo",{newTime:a}))}else x8(this,"seekTo",{newTime:a});w8(this,3,a);this.N("remotePlayerChange")}else u8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,y8(this,"stopVideo")):x8(this,"stopVideo");var a=t8(this);a.index=-1;a.videoId="";l8(a);v8(this,a);this.N("remotePlayerChange")}else u8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=t8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){C7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){C7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);x8(this,"setVolume",e)}c.muted=b;c.volume=a;v8(this,c)}else u8(this,g.Ra(this.setVolume,a,b))};
g.h.pA=function(a,b){if(1==this.g){var c=t8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Mg(b.style),g.ec(d,c.g));x8(this,"setSubtitlesTrack",d);v8(this,c)}else u8(this,g.Ra(this.pA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();x8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=t8(this);d.audioTrackId=c;v8(this,d)}else u8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=t8(this);c=c||0;var m={videoId:a,currentIndex:c};p8(l,a,c);g.Da(b)&&(n8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Mg(k));x8(this,"setPlaylist",m);d||v8(this,l)};
g.h.xn=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);p8(c,a,b);v8(this,c)}x8(this,"previous")}else u8(this,g.Ra(this.xn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);p8(c,a,b);v8(this,c)}x8(this,"next")}else u8(this,g.Ra(this.nextVideo,a,b))};
g.h.gv=function(){1==this.g?x8(this,"dismissAutoplay"):u8(this,this.gv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.Q.prototype.dispose.call(this)};
g.h.T=function(){jra(this);this.o=null;this.u.clear();r8(this,null);g.Q.prototype.T.call(this)};
g.h.nt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.nK=function(a,b){this.N(a,b)};
g.h.kI=function(a){if(!a)this.Bk(null),r8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=t8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)C7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,v8(this,b)}};
g.h.Bk=function(a){C7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),kra(this),this.N("remotePlayerChange")};
g.h.jI=function(a){a?(kra(this),this.N("remotePlayerChange")):this.Bk(null)};
g.h.Rs=function(){x8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.wI=function(){var a=gra();a&&r8(this,a)};
g.h.Jb=function(a){C7("CP",a)};g.t(z8,g.Q);g.h=z8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;n8(this.Oa,m);this.o="UNSUPPORTED";A8("Connecting with setPlaylist and params: "+g.Mg(l));this.g.connect({method:"setPlaylist",
params:g.Mg(l)},a,m6())}else A8("Connecting without params"),this.g.connect({},a,m6());mra(this)};
g.h.dispose=function(){this.da()||(this.N("beforeDispose"),B8(this,3));g.Q.prototype.dispose.call(this)};
g.h.T=function(){C8(this);E8(this);D8(this);g.bq(this.C);this.C=NaN;g.bq(this.D);this.D=NaN;this.l=null;g.es(this.P);this.P.length=0;this.g.dispose();g.Q.prototype.T.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.kD=function(){this.Sh(2)};
g.h.oI=function(){A8("Channel opened");this.I&&(this.I=!1,D8(this),this.H=g.$p((0,g.y)(function(){A8("Timing out waiting for a screen.");this.Sh(1)},this),15E3));
oqa(wqa(this.g),this.M)};
g.h.lI=function(){A8("Channel closed");isNaN(this.u)?p6(!0):p6();this.dispose()};
g.h.mI=function(a){p6();isNaN(this.Fj())?(A8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,A8("Channel error: "+a+" with reconnection in "+this.Fj()+" ms"),B8(this,2))};
g.h.nI=function(a){a.params?A8("Received: action="+a.action+", params="+g.Mg(a.params)):A8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=V5(a.params.devices);this.i=(0,g.G)(a,function(c){return new Y5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
pra(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
pra(this,!1);break;case "remoteConnected":var b=new Y5(V5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||cqa(this.i,b);
break;case "remoteDisconnected":b=new Y5(V5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":rra(this,a);break;case "nowPlaying":tra(this,a);break;case "onStateChange":sra(this,a);break;case "onAdStateChange":ura(this,a);break;case "onVolumeChanged":vra(this,a);break;case "onSubtitlesTrackChanged":qra(this,a);break;case "nowAutoplaying":wra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":xra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:A8("Unrecognized action: "+a.action)}};
g.h.eM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&F8(this,"getNowPlaying")}};
g.h.aD=function(){var a=3;this.da()||(a=0,isNaN(this.Fj())?x7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Sh=function(a){A8("Disconnecting with "+a);C8(this);this.N("beforeDisconnect",a);1==a&&p6();xqa(this.g,a);this.dispose()};
g.h.ZC=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),p8(a,this.l,a.index));return q8(a)};
g.h.tM=function(a){var b=new k8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.bq(this.C),this.C=g.$p((0,g.y)(this.eM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&o8(this.Oa)==o8(b)&&g.Mg(this.Oa.g)==g.Mg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
g.h.Vv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Fj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.C)():NaN};
g.h.SC=function(){return this.o||"UNSUPPORTED"};
g.h.TC=function(){return this.A||""};
g.h.bN=function(){if(!isNaN(this.Fj())){var a=this.g.i;g.zo(a.g);a.start()}};
g.h.mM=function(a,b){F8(this,a,b);ora(this)};
z8.prototype.subscribe=z8.prototype.subscribe;z8.prototype.unsubscribeByKey=z8.prototype.Hf;z8.prototype.getProxyState=z8.prototype.aD;z8.prototype.disconnect=z8.prototype.Sh;z8.prototype.getPlayerContextData=z8.prototype.ZC;z8.prototype.setPlayerContextData=z8.prototype.tM;z8.prototype.getOtherConnectedRemoteId=z8.prototype.Vv;z8.prototype.getReconnectTimeout=z8.prototype.Fj;z8.prototype.getAutoplayMode=z8.prototype.SC;z8.prototype.getAutoplayVideoId=z8.prototype.TC;z8.prototype.reconnect=z8.prototype.bN;
z8.prototype.sendMessage=z8.prototype.mM;g.t(G8,G7);g.h=G8.prototype;g.h.Jd=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.bo=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;G7.prototype.T.call(this)};
g.h.fN=function(){this.N("screenChange")};
g.h.RJ=function(){this.N("onlineScreenChange")};
P7.prototype.$_st=P7.prototype.start;P7.prototype.$_gspc=P7.prototype.gN;P7.prototype.$_gsppc=P7.prototype.nB;P7.prototype.$_c=P7.prototype.contains;P7.prototype.$_g=P7.prototype.get;P7.prototype.$_a=P7.prototype.add;P7.prototype.$_un=P7.prototype.bo;P7.prototype.$_r=P7.prototype.remove;P7.prototype.$_gs=P7.prototype.Jd;P7.prototype.$_gos=P7.prototype.mB;P7.prototype.$_s=P7.prototype.subscribe;P7.prototype.$_ubk=P7.prototype.Hf;var Z8=null,Y8=!1,H8=null,I8=null,X8=null,M8=[];g.t($8,g.H);g.h=$8.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.az,this);this.g.unsubscribe("remotePlayerChange",this.Dk,this);this.g.unsubscribe("remoteQueueChange",this.nn,this);this.g.unsubscribe("autoplayUpNext",this.Ey,this);this.g.unsubscribe("previousNextChange",this.Xy,this);this.g.unsubscribe("nowAutoplaying",this.Ty,this);this.g.unsubscribe("autoplayDismissed",this.Dy,this);this.g=this.u=null};
g.h.Cx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(c9(this)){if(!t8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==t8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Mj(c[0],c[1]);break;case "control_subtitles_set_track":d9(this,c[0]);break;case "control_set_audio_track":c=c[0],c9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();e9(this,0==c?void 0:c);break;case "control_seek":e9(this,c[0]);break;case "control_subtitles_set_track":d9(this,c[0]);break;case "control_set_audio_track":c=c[0],c9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.iI=function(a){this.I.gD(a)};
g.h.OM=function(a){this.Cx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.BA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||d9(this,a)};
g.h.Py=function(a){if(c9(this)){this.g.unsubscribe("remotePlayerChange",this.Dk,this);var b=Math.round(a.volume);a=!!a.muted;var c=t8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Dk,this)}};
g.h.kJ=function(){g.Xb(this.C)||Jra(this,this.C);this.D=!1};
g.h.az=function(a,b){this.A.stop();2==b&&this.AA()};
g.h.Dk=function(){if(c9(this)){this.o.stop();var a=t8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Em=1;break;case 1082:case 1083:this.u.Em=0;break;default:this.u.Em=-1}switch(a.playerState){case 1081:case 1:b9(this,new g.CC(8));this.zA();break;case 1085:case 3:b9(this,new g.CC(9));break;case 1083:case 0:b9(this,new g.CC(2));this.H.stop();a9(this,this.i.getVideoData().lengthSeconds);break;case 1084:b9(this,new g.CC(4));break;case 2:b9(this,new g.CC(4));a9(this,o8(a));
break;case -1:b9(this,new g.CC(64));break;case -1E3:b9(this,new g.CC(128,{errorCode:"mdx.remoteerror",message:"\u6b64\u89c6\u9891\u65e0\u6cd5\u8fdc\u7a0b\u64ad\u653e\u3002"}))}a=t8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,Jra(this,a));a=t8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.ZA()}else Ira(this)};
g.h.Xy=function(){this.i.N("mdxpreviousnextchange")};
g.h.nn=function(){c9(this)||Ira(this)};
g.h.oC=function(){this.g.gv()};
g.h.Ey=function(a){a&&(a=g.Xq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.sL,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.sL=function(a,b){var c=new g.nB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Ty=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Dy=function(){this.i.N("mdxautoplaycanceled")};
g.h.IF=function(a,b){-1==t8(this.g).playerState?e9(this,a):b&&this.g.seekTo(a)};
g.h.ZA=function(){if(c9(this)){var a=t8(this.g);this.l.La(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Py)}};
g.h.zA=function(){this.o.stop();if(!this.g.da()){var a=t8(this.g);1==a.playerState&&b9(this,new g.CC(8));a9(this,o8(a));this.o.start()}};
g.h.AA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(f9,g.W);f9.prototype.o=function(){X5("mdx-privacy-popup-cancel");this.l.hide()};
f9.prototype.A=function(){X5("mdx-privacy-popup-confirm");this.l.hide()};g.t(g9,g.W);g9.prototype.u=function(a){Lra(this,a.state)};g.t(h9,g.cU);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.dU(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.qe(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.pe=function(a){return"cast-selector-receiver"==a?"\u6295\u5c04\u2026":this.F[a].name};
h9.prototype.Jc=function(a){g.cU.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.VK);g.h=i9.prototype;
g.h.create=function(){Cra(g.$y(g.X(this.player)));this.l.push(g.gq("yt-remote-before-disconnect",this.fI,this));this.l.push(g.gq("yt-remote-connection-change",this.vK,this));this.l.push(g.gq("yt-remote-receiver-availability-change",this.Yy,this));this.l.push(g.gq("yt-remote-auto-connect",this.tK,this));this.l.push(g.gq("yt-remote-receiver-resumed",this.sK,this));this.l.push(g.gq("mdx-privacy-popup-confirm",this.VL,this));this.l.push(g.gq("mdx-privacy-popup-cancel",this.UL,this));this.Yy()};
g.h.load=function(){this.player.cancelPlayback();g.VK.prototype.load.call(this);this.u=new $8(this,this.player,this.g);var a=(a=Hra())?a.currentTime:0;var b=W8()?new s8(R8(),void 0):null;0==a&&b&&(a=o8(t8(b)));0!=a&&this.sd(a);Kra(this,this.jk,this.jk);g.bY(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.o=this.i;g.qf(this.u,this.g);this.g=this.u=null;g.VK.prototype.unload.call(this);g.bY(this.player.app,5)};
g.h.T=function(){g.hq(this.l);g.VK.prototype.T.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Cx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Em};
g.h.cD=function(){return this.loaded?this.u.suggestion:null};
g.h.Le=function(){return this.g?t8(this.g).Le:!1};
g.h.hasNext=function(){return this.g?t8(this.g).hasNext:!1};
g.h.sd=function(a,b){this.H=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=t8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+m8(a):a.l,isAtLiveHead:1>=(a.u?a.i+m8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+m8(a):a.i,seekableStart:0<a.o?a.o+
m8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.xn=function(){this.g&&this.g.xn()};
g.h.fI=function(a){1==a&&(this.C=this.g?t8(this.g):null)};
g.h.vK=function(){var a=W8()?new s8(R8(),void 0):null;if(a){var b=this.o;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.o=b,this.load())}else g.pf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,o8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Yy=function(){this.A=[this.i].concat(Era());var a=S8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.tK=function(){var a=S8();j9(this,a)};
g.h.sK=function(){this.o=S8()};
g.h.VL=function(){this.D=!0;Y8=!1;Z8&&U8(Z8,1);Z8=null};
g.h.UL=function(){this.D=!1;j9(this,this.i);this.player.playVideo()};
g.h.Zb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?i8():j9(this,b)),this.loaded?this.o:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&i8(),!0):!1}};
g.h.Rs=function(){this.g.Rs()};
g.h.Ib=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.sV.remote=i9;})(_yt_player);
